# Introduction to Deep Learning


## Motivation
With the rise of digitalization the availability of data has changed drastically:
<table><tr>
<td> <img src="figures/Introduction_DL/BigData_001.png" alt="Drawing" style="width: 200px;"/> </td>
<td> <img src="figures/Introduction_DL/devices.png" alt="Drawing" style="width: 200px;"/> </td>
</tr>
</table><br>
<center><b>Figure 1:</b> Data collection now and then.</center>

Data becomes more and more important.

<center><i>The world's most valuable resource is no longer oil, but data.</i></center>
<center><img src="figures/Introduction_DL/oil.png" alt="Drawing" style="width: 400px;"/><br>
<b>Figure 2:</b> From: The Economist (May 6th, 2017).</center>

**But:** (Big) Data has no value, per se.<br> The crucial question is what can be learned from the data and what conclusions can be drawn?


$\Rightarrow$ Two main tasks are **prediction** and **causal inference**.

## Breakthroughs and Applications of Machine Learning
<table><tr>
<td> <img src="figures/Introduction_DL/alphago.png" alt="Drawing" style="width: 250px;"/> </td>
<td> <img src="figures/Introduction_DL/nature.png" alt="Drawing" style="width: 250px;"/> </td>
</tr></table><br>
<center><b>Figure 3:</b> Alpha Go.</center>


<center><img src="figures/Introduction_DL/ml-translation.png" alt="Drawing" style="width: 800px;"/><br>
<b>Figure 4:</b> Google Translate. From: https://uk.pcmag.com/internet-3/86069/google-expands-neural-networks-for-language-translation.</center>

<table><tr>
<td> <img src="figures/Introduction_DL/chart_top1.png" alt="Drawing" style="width: 400px;"/> </td>
<td> <img src="figures/Introduction_DL/chart_top5.png" alt="Drawing" style="width: 400px;"/> </td>
</tr></table><br>
<center><b>Figure 5:</b> Change in Performance for Image Classification. From: https://paperswithcode.com/sota/image-classification-on-imagenet.</center>

<center><img src="figures/Introduction_DL/street.png" alt="Drawing" style="width: 600px;"/><br>
<b>Figure 6:</b> Object Detection and Segmentation. From: https://github.com/matterport/Mask_RCNN.</center>

<table cellspacing="0" cellpadding="0"><tr>
<td> <img src="figures/Introduction_DL/person_1.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/person_2.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/person_3.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/person_4.jpg" alt="Drawing" style="width: 300px;"/> </td>
</tr><tr>
<td> <img src="figures/Introduction_DL/person_5.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/person_6.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/person_7.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/person_8.jpg" alt="Drawing" style="width: 300px;"/> </td>
</tr></table><br>
<center><b>Figure 7:</b> Generate Faces. From: https://thispersondoesnotexist.com/</center>

<center><img src="figures/Introduction_DL/DL_art_pic2.jpg" alt="Drawing" style="width: 600px;"/><br>
<b>Figure 8:</b> "Edmond de Belamy". From: Christie's.</center>

<table cellspacing="0" cellpadding="0"><tr>
<td></td>
<td> <img src="figures/Introduction_DL/venice-boat.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td></td>
</tr><tr>
<td> <img src="figures/Introduction_DL/g2.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/g7.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/g9.jpg" alt="Drawing" style="width: 300px;"/> </td>
</tr><tr>
<td> <img src="figures/Introduction_DL/style_1.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/style_2.jpg" alt="Drawing" style="width: 300px;"/> </td>
<td> <img src="figures/Introduction_DL/style_3.jpg" alt="Drawing" style="width: 300px;"/> </td>
</tr></table><br>
<center><b>Figure 9:</b> Neural Style transfer. From: https://github.com/StacyYang/MXNet-Gluon-Style-Transfer</center>

### Examples in Different Domains

- Near-human-level image classification
- Near-human-level speech recognition
- Near-human-level handwriting transcription
- Improved machine translation
- Improved text-to-speech conversion
- Near-human-level autonomous driving
- Improved search results on the web
- Ability to answer natural language questions


## Artificial Intelligence, Machine Learning and Deep Learning

There are a lot of terms, which are often used when talking about deep learning.<br> 
Let us clarify the relationship between artificial intelligence, machine learning and deep learning.

<center><img src="figures/Introduction_DL/AI_ML_DL.png" alt="Drawing" style="width: 400px"/>
<br></center>
<center><b>Figure 10:</b> Relationship between AI, machine learning and deep learning.</center>

### The Machine Learning Paradigm
Classical programming takes data and explicit, designed rules as input to produce an output.

<center>
<img src="./figures/Introduction_DL/intro_ml_paradigm_1.png" alt="Drawing" style="width: 800px;"/><br>
<b>Figure 11:</b> Classical programming.</center>

Instead machine learning "learns" to design rules from data and the corresponding answers.

<center>
<img src="./figures/Introduction_DL/intro_ml_paradigm_2.png" style="width: 800px;"/><br>
<b>Figure 12:</b> Machine learning.</center>

### When to use Deep Learning

As there are a lot of different machine learning algorithms (eg. boosting, random forests,...) the question is when to use deep learning or why deep learning has become so popular over the last years.

<center>
<img src="./figures/Introduction_DL/DLvsML.png"  style="width: 400px;"/><br></center>
<center><b>Figure 13:</b> Comparison of deep learning and traditional machine learning algorithms.</center>

In general, deep learning will outperform most of the other machine learning methods, if the amount of data is very huge.

###  Expressions 

As the deep learning community has some unique expressions, which might be called differently in statistic literature, we provide a list of synonymous expressions

- Training/Learning/Estimating
- Weights/Parameters
- Outcome/Label/Dependent Variable
- Feature/Input/Regressor/Independent Variable

## Software
There are several different deep learning software-frameworks (cf. [Deep Learning Software](https://en.wikipedia.org/wiki/Comparison_of_deep-learning_software))

In this lecture, we will use [Pytorch](https://pytorch.org/). Pytorch is an open source machine learning framework, which is also very popular in companies (another large platform is [Tensorflow](https://www.tensorflow.org/)).
Pytorch is based on Python, such that you will require some additional prerequisites (like Python etc.). As you will write your own code in the tutorials, you have to get access to Pytorch.

You can either use a [local installation](https://pytorch.org/get-started/locally/) (using Anaconda can be really helpful) or use some online solutions as [Colab](https://colab.research.google.com/notebooks/intro.ipynb) or 
[Kaggle](https://www.kaggle.com/docs/notebooks) (which require registrations, but might be very easy to set up, since you do not need to install packages).


## Tensors and Linear Algebra

Before we start to learn any concepts of machine learning, we will start be introducing some basic mathematics and the corresponding implementation in Pytorch.

Deep learning heavily relies on working with large datasets, which can be represented as matrices, where the rows represent the observations and the columns the corresponding attributes or features. Therefore, basic operations from linear algebra are highly useful.

<center><img src="figures/Introduction_DL/matrix_small.png" alt="Drawing" style="width: 800px;"/></center>

In Pytorch the data is stored in the `tensor class`. A tensor is the $n$-dimensional array of numerical values. Therefore, tensors are a generalization of a matrix, such as matrices are the two-dimensional generalization of vectors. 

The `tensor class` from Pytorch is similar to `ndarray class` from NumPy, but includes some important additional features, such as GPU-support and automatic differentiation support.

### Create Tensors
To create a tensor we start by importing the torch module and creating some basic tensors.

In [1]:
import torch
x = torch.arange(42)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41])


Next, we list some of the most basic forms of properties and operations on tensors.

In [2]:
print(x.shape)

torch.Size([42])


If we want to reshape the data, the reshape command (as in NumPy) is very helpful.

In [3]:
X = x.reshape(6,7)
print(X) 
print(X.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]])
torch.Size([6, 7])


This is the same as

In [4]:
X = x.reshape(6,-1)
print(X) 
print(X.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]])
torch.Size([6, 7])


In [5]:
X = x.reshape(-1,7)
print(X) 
print(X.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]])
torch.Size([6, 7])


Instead of reshaping a vector to specific shape, we can specify the tensor directly.

In [6]:
print(torch.tensor([[1,2],[3,4],[5,6]]))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In general, we initialize tensors with random values, ones or zeros by specifying the dimensions.

In [7]:
zeros = torch.zeros(2,3,4)
print(zeros)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
ones = torch.ones(2,3,4)
print(ones)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [9]:
random_tensor = torch.randn(2,3,4)
print(random_tensor)

tensor([[[ 1.1431e+00,  1.7184e+00,  2.0493e-02, -3.0263e-01],
         [ 8.9599e-01, -1.3769e+00, -1.0565e+00, -1.1656e+00],
         [-1.2166e+00, -2.0612e+00,  1.4955e+00, -7.4260e-02]],

        [[-1.3707e+00,  2.0854e+00,  6.5237e-01, -9.0319e-01],
         [ 4.1972e-01, -1.5094e-03,  2.8426e-01, -3.4373e-01],
         [-2.0581e+00, -1.5252e-01,  7.8396e-01, -6.8375e-02]]])


Here, `torch.randn` creates randomly drawn entries, where each entry is drawn independently from a standard normal distribution.

### Tensor Operations

#### Basic Operations

The most common arithmetic operators (addition, subtraction, multiplication, division and  exponentiation) are implemented to work elementwise on the tensor class for two tensors of the same shape.

In [10]:
x = torch.tensor([3.0,2])
y = torch.tensor([4.0,1])
print(x+y, x-y, x*y, x/y, x**2)

tensor([7., 3.]) tensor([-1.,  1.]) tensor([12.,  2.]) tensor([0.7500, 2.0000]) tensor([9., 4.])


Additionally, some common functions as the exponential or logarithmic function are implemented and executed elementwise.

In [11]:
a = torch.exp(x)
print(a, torch.log(a))

tensor([20.0855,  7.3891]) tensor([3., 2.])


Further, combining tensors is a very important operation, which can be performed with the concatenate operation (`torch.cat`). To use `torch.cat`, two compatible tensors and the axis to concatenate along have to specified.

In [12]:
cat_0 = torch.cat((zeros,ones), dim = 0)
print(cat_0)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [13]:
cat_1 = torch.cat((zeros,ones), dim = 1)
print(cat_0, cat_1)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [14]:
print(torch.cat((zeros,ones), dim = 2))

tensor([[[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]])


Moreover, logical statements and some other basic operations can be easily used for tensors.

In [15]:
print(x,y,x < y)

tensor([3., 2.]) tensor([4., 1.]) tensor([ True, False])


In [16]:
print(x.sum(),x.mean())

tensor(5.) tensor(2.5000)


The concept of *Broadcasting* is very useful to simplify some calculations.<br> As seen above the elementwise operations, need the tensors to be of the same shape. 

Under certain conditions, the elementwise operations can even be applied to tensors of different shape.

In [17]:
x = torch.tensor([[3.0],[2]])
y = torch.tensor([[4.0,1,2]])
print(x.shape, y.shape)

torch.Size([2, 1]) torch.Size([1, 3])


In [18]:
z = x+y
print(z,z.shape)

tensor([[7., 4., 5.],
        [6., 3., 4.]]) torch.Size([2, 3])


As you can observe, the tensor $x$ (dimension $2\times 1$) and $y$ (dimension $1\times 3$) are broadcasted to the same shape ($2\times 3$) with an subsequent elementwise operation:
$$x+y = \begin{pmatrix} 3 & 3 &3 \\ 2 & 2 & 2\end{pmatrix}+\begin{pmatrix} 4 & 1 &2 \\ 4 & 1 & 2\end{pmatrix}= \begin{pmatrix}7 & 4 &5 \\ 6 & 3 & 4\end{pmatrix}$$


Further, specific elements can be accessed with indexing and slicing operations

In [19]:
a = torch.arange(12).reshape(-1,4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [20]:
print(a[0,0], a[0,:], a[0:2,0])

tensor(0) tensor([0, 1, 2, 3]) tensor([0, 4])


In [21]:
print(a[:,3], a[:,-1])

tensor([ 3,  7, 11]) tensor([ 3,  7, 11])


As many some functions need NumPy arrays converting converting tensors is very helpful.

In [22]:
b = a.numpy()
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
print(torch.tensor(b))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


#### Linear Algebra

Recall that a lot of tensors will be matrices or vectors. Therefore, operations from linear algebra will be very helpful. At first we will take a look at dot products.
Let 

$$x = \begin{pmatrix}x_1\\
x_2\\ \vdots\\x_p \end{pmatrix}\in \mathbb{R}^p,y= \begin{pmatrix}y_1\\
y_2\\ \vdots\\y_p \end{pmatrix}\in \mathbb{R}^p,$$ 

then 

$$\langle x, y\rangle = x^Ty := \sum_{i=1}^p x_iy_i, $$

which is implemented with `torch.dot`.

In [24]:
x = torch.arange(3, dtype = torch.float32)
y = torch.ones(3, dtype = torch.float32)
print(x, y, torch.dot(x, y))

tensor([0., 1., 2.]) tensor([1., 1., 1.]) tensor(3.)


Let 

$$A=\begin{pmatrix}a_{1,1}&a_{1,2}&\cdots& a_{1,p}\\
a_{2,1}&a_{2,2}&\cdots& a_{2,p}\\
\vdots&\vdots&\ddots&\vdots\\
a_{n,1}&a_{n,2}&\cdots&a_{n,p}\end{pmatrix}\in\mathbb{R}^{n\times p}$$ 


and $x\in \mathbb{R}^p$ then the matrix-vector product is defined as

$$Ax:=\begin{pmatrix}\sum_{j=1}^n a_{1,j} x_j\\
\vdots\\
\sum_{j=1}^n a_{n,j} x_j\end{pmatrix}=\begin{pmatrix} a_{1,\bullet}^T x_j\\
\vdots\\
a_{n,\bullet}^T x_j\end{pmatrix}\in \mathbb{R}^n,$$

where $a_{i,\bullet}^T$ denotes the $i$-th row of $A$.

We can use `torch.mv`

In [25]:
A = torch.tensor([[3,1.3,0],[2,5,0.5]])
print(A.shape,x.shape)

torch.Size([2, 3]) torch.Size([3])


In [26]:
print(torch.mv(A, x))

tensor([1.3000, 6.0000])


Let $B\in \mathbb{R}^{p\times q}$. Then the generalization to matrix-matrix product is straightforward.

$$AB=\begin{pmatrix}a_{1,\bullet}^T b_{\bullet,1}&a_{1,\bullet}^T b_{\bullet,2}&\cdots& a_{1,\bullet}^T b_{\bullet,q}\\
a_{2,\bullet}^T b_{\bullet,1}&a_{2,\bullet}^T b_{\bullet,2}&\cdots& a_{2,\bullet}^T b_{\bullet,q}\\
\vdots&\vdots&\ddots&\vdots\\
_{n,\bullet}^T b_{\bullet,n}&a_{1,\bullet}^T b_{\bullet,2}&\cdots& a_{n,\bullet}^T b_{\bullet,q}
\end{pmatrix},$$

where $b_{\bullet,j}$ denotes the $j$-th column of $B$. This can be done with `torch.mm`.

In [27]:
B = torch.ones((3,2))
print(torch.mm(A,B))

tensor([[4.3000, 4.3000],
        [7.5000, 7.5000]])


Let $x\in\mathbb{R}^n$ be vector. A **vector-norm** is a function $f:\mathbb{R}^n\to [0,\infty)$ with the following properties

1. For $\alpha\in \mathbb{R}$ it holds: $f(\alpha x)=|\alpha|f(x)$.
2. For $x,y\in\mathbb{R}^n$ it holds: $f(x+y)\le f(x)+f(y)$.
3. It holds: $f(x)=0 \Leftrightarrow x=0\in \mathbb{R}^n$.

If only properties 1. and 2. hold, $f$ is called a seminorm.

The most common norm is the euclidean norm 

$$\begin{aligned}\|\cdot\|_2:&\mathbb{R}^n\to [0,\infty)\\ 
&x\mapsto \left(\sum\limits_{i=1}^n x_i^2\right)^{1/2}
\end{aligned}.$$

In [28]:
print(x,torch.norm(x))

tensor([0., 1., 2.]) tensor(2.2361)


The euclidean norm is a special case of the $L_p$-norm 

$$\begin{aligned}\|\cdot\|_p:&\mathbb{R}^n\to [0,\infty)\\ 
&x\mapsto \left(\sum\limits_{i=1}^n x_i^p\right)^{1/p}
\end{aligned},$$

where the $L_1$-norm is an important case. How does the $L_1$-norm behave differently than the $L_2$-norm?

A **matrix-norm** has the same properties as a vector norm, but is defined for matrices (in general norms are defined on vector spaces).

Let $A\in \mathbb{R}^{n\times m}$. The **Frobenius norm** 

$$\begin{aligned}\|\cdot\|_F:&\mathbb{R}^{n\times m}\to [0,\infty)\\ 
&A\mapsto \left(\sum\limits_{i=1}^n\sum_{j=1}^m a_{i,j}^2\right)^{1/2}.
\end{aligned}$$

In [29]:
print(A,torch.norm(A))

tensor([[3.0000, 1.3000, 0.0000],
        [2.0000, 5.0000, 0.5000]]) tensor(6.3198)


The Frobenius norm is a special case of the $L_{p,q}$-norm 

$$\begin{aligned}\|\cdot\|_{p,q}:&\mathbb{R}^{n\times m}\to [0,\infty)\\ 
&A\mapsto \left(\sum\limits_{j=1}^m\left(\sum_{i=1}^n a_{i,j}^p\right)^{q/p}\right)^{1/q}.
\end{aligned}$$